// Resend API Client for BreakIn
// Docs: https://resend.com/docs/api-reference

import { prisma } from "@/lib/db";

const RESEND_BASE_URL = "https://api.resend.com";

const FROM_FR = "Ousmane Thienta <candidatures@ousmanethienta.com>";
const FROM_EN = "Ousmane Thienta <applications@ousmanethienta.com>";

async function getResendApiKey(): Promise<string> {
  const setting = await prisma.setting.findUnique({
    where: { key: "resendApiKey" },
  });
  return setting?.value || process.env.RESEND_API_KEY || "";
}

export interface ResendSendOptions {
  to: string;
  subject: string;
  body: string;
  language?: string;
  html?: string;         // Optional pre-formatted HTML (overrides auto-generated HTML)
  attachments?: Array<{ filename: string; content: string }>;
}

export async function sendEmailViaResend(options: ResendSendOptions) {
  const apiKey = await getResendApiKey();
  if (!apiKey) {
    throw new Error("Resend API key not configured. Add it in Settings (key: resendApiKey).");
  }

  const from = (options.language ?? "fr") === "en" ? FROM_EN : FROM_FR;

  // Use provided HTML or generate from plain text body
  const htmlBody = options.html ||
    `<div style="font-family: Arial, sans-serif; font-size: 14px; line-height: 1.6; color: #333;">${options.body.replace(/\n/g, "<br>")}</div>`;

  const response = await fetch(`${RESEND_BASE_URL}/emails`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      from,
      to: options.to,
      subject: options.subject,
      html: htmlBody,
      text: options.body,
      ...(options.attachments ? { attachments: options.attachments } : {}),
    }),
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`Resend send error ${response.status}: ${text}`);
  }

  return response.json();
}


// ---------- Recap Email ----------

export interface SendRecapEmailOptions {
  type: string;    // "daily" or "weekly"
  period: string;  // "2026-04-05" or "2026-W14"
  content: string; // Markdown content
}

export async function sendRecapEmail(options: SendRecapEmailOptions) {
  const { type, period, content } = options;

  const subject = type === "daily"
    ? `BreakIn — Recap du ${period}`
    : `BreakIn — Recap semaine ${period}`;

  // Convert Markdown to simple HTML
  const htmlContent = content
    .replace(/^# (.+)$/gm, '<h1 style="color: #1a1a1a; border-bottom: 2px solid #e5e5e5; padding-bottom: 8px;">$1</h1>')
    .replace(/^## (.+)$/gm, '<h2 style="color: #333; margin-top: 24px;">$1</h2>')
    .replace(/^### (.+)$/gm, '<h3 style="color: #555;">$1</h3>')
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/^- (.+)$/gm, '<li style="margin: 4px 0;">$1</li>')
    .replace(/(<li[^>]*>.*<\/li>\n?)+/g, '<ul style="padding-left: 20px;">$&</ul>')
    .replace(/\| (.+) \|/g, (match) => {
      const cells = match.split("|").filter(Boolean).map((c) => c.trim());
      return `<tr>${cells.map((c) => `<td style="padding: 6px 12px; border: 1px solid #ddd;">${c}</td>`).join("")}</tr>`;
    })
    .replace(/(<tr>.*<\/tr>\n?)+/g, '<table style="border-collapse: collapse; width: 100%; margin: 16px 0;">$&</table>')
    .replace(/\n/g, "<br>");

  const html = `
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; color: #1a1a1a;">
      ${htmlContent}
      <hr style="border: none; border-top: 1px solid #e5e5e5; margin: 32px 0 16px;">
      <p style="font-size: 12px; color: #999;">
        Generated by BreakIn at ${new Date().toISOString()}<br>
        <a href="https://breakin-lyart.vercel.app" style="color: #666;">Open BreakIn Dashboard</a>
      </p>
    </div>
  `;

  return sendEmailViaResend({
    to: "ousmane.thienta@audencia.com",
    subject,
    body: content,
    language: "fr",
    html,
  });
}
